export enum TextFieldID {
    NAME = "name",
    FAMILYNAME = "familyname",
    COMPANYNAME = "companyname",
    EMAIL = "email",
    PASSWORD1 = "password1",
    PASSWORD2 = "password2",
    TEL_NR = "telNr",
    BIRTH ="birth",
    BUNDESLAND = "bundesland",
    STREET = "street",
    NR = "nr",
    ZIPCODE = "zipcode",
    CITY = "city",
    ISCARDEALER = "isCarDealer",
    ISCHAT = "isChat",
    ISTELEFON = "isTelefon",
    ISEMAIL = "esEmail",
    IMPRESSUMDATEN = "impressumdaten"
}